development:
  adapter: postgresql
  database: cookie_quiz_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: cookie_quiz_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: cookie_quiz_production
  pool: 5
  timeout: 5000